add banner for projects where whole team from Ukraine. refs #120
vshymanskyy/StandWithUkraine pull request #121
Opened 2022-04-17 16:24 UTC by dmitry-sinina

2022-04-17 22:06 UTC, webknjaz commented
I believe that this needs to be wired to the templating setup we have now. As for the wording, it seems grammatically correct, no objections for me.

2022-04-17 22:26 UTC, dmitry-sinina commented
>I believe that this needs to be wired to the templating setup we have now.

What templating you saying about?

2022-04-19 21:49 UTC, webknjaz commented
https://github.com/vshymanskyy/StandWithUkraine/blob/d1f0c46/generate.js#L55-L59

cc @mourner

2022-04-19 22:22 UTC, mourner requested changes
A grammar nit aside from templating

2022-04-19 22:22 UTC, mourner commented on banner-direct-team.svg
> +      <tspan x="25" dy="0.45em">This project is created by the team from Ukraine.</tspan>
The team -> a team

2022-04-20 13:28 UTC, mourner approved these changes

2022-04-20 13:47 UTC, merged